### ISSUE TITLE
[Suggestion] "Mark all as read" / "Mark as read" on rightclick menu

### ISSUE THREAD

**Issue by Soukyuu** [anthon38/gmailfeed#1]
Thanks for the plasmoid, seems to be working fine so far. I'm missing an option to mark all mails as read, as well as marking individual mails as read without having to open inbox. Any chance of adding this?

**Comment by anthon38** [comment]
Sorry but it's not the plan right now, I'd even say it's unlikely. 
If you want something more featureful, I recommend using an actual email client.
