### ISSUE TITLE
"Google hasn't verified this app" on account creation

### ISSUE THREAD

**Issue by elbowz** [anthon38/gmailfeed#12]
Hey @anthon38,

 I really love your plasmoid, and some months ago it was stopping working (error "Host requires authentication" but I cannot re-configure  it in any way).

I'm very glad to see an update (v1.2) and now the error is become: "Please configure an Account"
but when I try to add a Gmail feed account, following the step to login on google, appear this page/screen:
![Screenshot_20220610_104041](https://user-images.githubusercontent.com/1451484/173030256-a7b47ce9-a19f-452b-ae13-213d99fa6009.png)

Thanks in advance!

**Comment by anthon38** [comment]
Hello, just click on "Advanced" at the bottom left and you should be able to continue the login process.
Google now wants to verify every app that access their services, and it's not an easy process for developpers, so for now, and as long as it still works, I won't bother with that...

**Comment by elbowz** [comment]
oooh shit, I'm really silly!
Works like a charm! 

Thaaaaaaaaanks a lot for this projet, your work and time spent :)
