### ISSUE TITLE
plasma 6 support

### ISSUE THREAD

**Issue by miku84** [anthon38/gmailfeed#14]
Hello!

Are there any plans for this great tool to support plasma 6? I have just upgraded to 6 and i can see that is not yet compatible with it.

Thanks

**Comment by anthon38** [comment]
Hello, I just upgraded to Plasma 6 myself and now I just need to find a bit of spare time to port it...
So yes I plan to do it but I can't tell you when exactly.
Thank you for your patience.

**Comment by anthon38** [comment]
The port to Plasma 6 is completed. 
Let me know if you run into any issues.
Anthony.

**Comment by miku84** [comment]
Thanks, all fine on with the AUR version on Manjaro :+1:
